<header>
	<nav>
			<img class="jam" id="jam" src="images/gooseberry.png" width="50" height="60" alt="jam_mascot">
		<form class="menu" action="index.php" method="get">
		<button class="menu_button">Home</button>
		</form>
		<form class="menu" action="topic.php" method="get">
		<button class="menu_button">Information</button>
		</form>
		<form class="menu" action="quiz.php" method="get">
		<button class="menu_button">Quiz Page</button>
		</form>
		<form class="menu" action="enhancement.html" method="get">
		<button class="menu_button">Enhancements</button>
		</form>
		<form class="menu" action="phpenhancements.php" method="get">
		<button class="menu_button">PHP Enhancements</button>
		</form>
		<form class="menu" action="references.html" method="get">
		<button class="menu_button">References</button>
		</form>
		<form class="menu" action="manage.php" method="get">
		<button class="menu_button">Quiz Administrator</button>
		</form>
	</nav>
</header>